[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    # This is the most compatible setting for Firebase popups
    Cross-Origin-Opener-Policy = "unsafe-none"
    Cross-Origin-Embedder-Policy = "unsafe-none"
